---

install_group_packages_list:
  - group: llvm
    packages:
      - cmake
      - gcc
      - g++
      - python
      - zlib
      - make
      - bzip2
      - tar
      - unzip
      - zip
  - group: math
    packages:
      - tar
  - group: system
    packages:
      - tar
