vm_list:
  - name: ubuntu_1
    iface_list:
      - ip: 192.168.1.20
        mac: 2a:7a:b8:15:7c:6a
    uuid: 912a696b-6a31-3caa-f445-fc30321e7a35
    vcpu: 3
    memory_KiB: "{{ 16 * 1024 * 1024 }}"
    base_os: ubuntu22.04
    resized_volume:
      disk_size: 192G
      expand_partition: /dev/sda3
      expand_lv: /dev/ubuntu-vg/ubuntu-lv
    meta:
      state: none
      host: kvm_1
