vm_list:
  - name: rocky_1
    iface_list:
      - ip: 192.168.1.20
        mac: 46:38:51:8e:0e:bb
    uuid: 3b6346a3-99fe-4aea-62e1-b75d4a85df57
    vcpu: 8
    memory_KiB: "{{ 32 * 1024 * 1024 }}"
    base_os: rocky9.0
    resized_volume:
      disk_size: 100G
      expand_partition: /dev/sda2
      expand_lv: /dev/rl/root
    meta:
      state: none
      host: kvm_1
  - name: rocky_2
    iface_list:
      - ip: 192.168.1.21
        mac: 5a:73:02:a8:f5:ff
    uuid: 17ba4b69-0dcc-0ef1-7549-3885abe5b01c
    vcpu: 8
    memory_KiB: "{{ 32 * 1024 * 1024 }}"
    base_os: rocky9.0
    resized_volume:
      disk_size: 100G
      expand_partition: /dev/sda2
      expand_lv: /dev/rl/root
    meta:
      state: none
      host: kvm_2

  - name: ubuntu_1
    iface_list:
      - ip: 192.168.1.30
        mac: 2a:7a:b8:15:7c:6a
    uuid: 912a696b-6a31-3caa-f445-fc30321e7a35
    vcpu: 8
    memory_KiB: "{{ 32 * 1024 * 1024 }}"
    base_os: ubuntu22.04
    resized_volume:
      disk_size: 100G
      expand_partition: /dev/sda3
      expand_lv: /dev/ubuntu-vg/ubuntu-lv
    meta:
      state: none
      host: kvm_1
  - name: ubuntu_2
    iface_list:
      - ip: 192.168.1.31
        mac: 6a:11:26:40:0b:d4
    uuid: 5e966a7d-ad15-431a-3125-ab8ce8619bda
    vcpu: 8
    memory_KiB: "{{ 32 * 1024 * 1024 }}"
    base_os: ubuntu22.04
    resized_volume:
      disk_size: 100G
      expand_partition: /dev/sda3
      expand_lv: /dev/ubuntu-vg/ubuntu-lv
    meta:
      state: none
      host: kvm_2
